### ISSUE TITLE
sponsors logos vary in size, makes for ugly view

### ISSUE THREAD

**Issue by Zandrr** [HackCU/LocalHackDay2016#1]
![image](https://cloud.githubusercontent.com/assets/4897485/19656971/627c5a56-99df-11e6-8cbb-1e3876888acb.png)

**Comment by daswisher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix sponsor logos on site](https://trello.com/c/1c1f8SNM/102-fix-sponsor-logos-on-site)

**Comment by daswisher** [comment]
Thanks for opening this! We just updated the site. We're using browser caching that keeps the content cached for 4 hours. So if it doesn't update, try clearing your browser cache. :)

**Comment by Zandrr** [comment]
muchhhhh nicer :)
