### ISSUE TITLE
Change pictures on other sections

### ISSUE THREAD

**Issue by casassg** [HackCU/LocalHackDay2016#21]
We should update to new pictures of Boulder in the page. The current ones are nice, but something like what we have in the header would be nicer. Not sure if @elliotwhitehead has other images.

**Comment by elliotwhitehead** [comment]
Thanks for adding that first one @casassg! Did you end up compressing it? I remember seeing someone said it took a while to download (the one I sent to slack was a hi-res desktop photo version haha. 

if not, I really like [this tool](http://webresizer.com/resizer/) for resizing / compressing images for web.

I'll look at other photos when I have a sec. I'm pretty slammed for the moment getting ready for GitHub Universe 😬

**Comment by casassg** [comment]
No worries, I did compress it with pngoptim and other. @AparaV can you share the issue where you found it?

**Comment by AparaV** [comment]
Yeah. @dawsbot had opened a PR on the HackCU III website repo where he compressed the images. He also documented the process there - https://github.com/HackCU/HackCU2017/pull/14

**Comment by casassg** [comment]
Closing this as its old. Not sure if we still have it pending.
