### ISSUE TITLE
Use full Local Hack Day Logo with GitHub branding

### ISSUE THREAD

**Issue by elliotwhitehead** [HackCU/LocalHackDay2016#24]
What would y'all think about using the full Local Hack Day seen [here](https://localhackday.mlh.io/)? 

I'm referring specifically to the banner beneath with "Hosted by GitHub".

I think having the Hosted by GitHub is powerful branding that could encourage better attendance. 

I'm aware right beneath that logo we currently have 'Hosted by Hack CU', but perhaps we could change that to something along the lines of 'Presented by HackCU' or 'Organized by HackCU'.

I just think keeping the GitHub branding adds credibility to the event for people who are first seeing about it.

Thoughts?

**Comment by elliotwhitehead** [comment]
P.s. I do have an email from MLH confirming that we can use that logo, along with an original SVG they provided for us to use.

**Comment by AparaV** [comment]
@elliotwhitehead yeah, we can totally change the logo and the text below it. Do you want to do that? If you're busy, you can share the logo on slack and the one who is least busy can get to it ASAP.

**Comment by casassg** [comment]
Mmm. Even though I love github, given the fact that we have sponsors I wouldn't put Github there. It may be a conflict of interests for other sponsors who are paying us (and not MLH like Github). I agree on adding Github under our sponsors sections though

**Comment by elliotwhitehead** [comment]
I suppose that's a good point. Hm. What if we used the full LHD logo with GitHub on printed posters, but not on the website?
